Fixes for list / create deployment in self hosted mode
patr-cloud/patr pull request #44
Opened 2024-09-19 05:46 UTC by argha-dot

- moved workspace sidebar card to it's own component
 - setting dummy 'last_used_workspace_id' to `Uuid::nil()` when the app is self-hosted
 - added `AppType` struct to determine if the app is self-hosted or managed
 - conditionally rendering parts of login, sign up, create deployment, and deployment list pages depending on the `AppType`

2024-09-19 22:55 UTC, rakshith-ravi requested changes

2024-09-19 22:55 UTC, rakshith-ravi commented on hosted-frontend/src/pages/auth/login.rs
> +						last_used_workspace_id: Some(Uuid::nil()),
Shouldn't this be decided based on the app_type?

2024-09-19 22:55 UTC, rakshith-ravi commented on hosted-frontend/src/pages/auth/sign_up.rs
> +				Ok(CreateAccountResponse {}) => {
Same - should be based on app_type

2024-09-19 22:55 UTC, rakshith-ravi commented on runners/common/src/routes/workspace/deployment/list_deployment.rs
> -			let repository_id = row.try_get::<Uuid, _>("repository_id")?;
Why remove this?

2024-09-20 06:37 UTC, argha-dot commented on runners/common/src/routes/workspace/deployment/list_deployment.rs
> -			let repository_id = row.try_get::<Uuid, _>("repository_id")?;
Right now, there's no repository_id row in the deployments table. I thought we would only support external registries.
I can add the repository_id to everything if that's not the case

2024-09-20 07:15 UTC, argha-dot commented on hosted-frontend/src/pages/auth/login.rs
> +						last_used_workspace_id: Some(Uuid::nil()),
Missed this, I'll put a fix for this in the next commit?,

2024-09-20 07:42 UTC, rakshith-ravi commented on runners/common/src/routes/workspace/deployment/list_deployment.rs
> -			let repository_id = row.try_get::<Uuid, _>("repository_id")?;
Hmm, repository ID usually references Patr's repository table. I suppose since we don't have that table, we can get away with just image name. Should be fine

2024-09-20 21:00 UTC, rakshith-ravi approved these changes, later dismissed
One small typo. The rest of it looks good to me

2024-09-20 21:00 UTC, rakshith-ravi commented on hosted-frontend/src/queries/infrastructure/deployment/mod.rs
> +pub fn udpdate_deployment_query() -> Action<
Small typo

2024-09-20 21:00 UTC, rakshith-ravi commented
Not sure why this is marked as draft. Lmk when this is good to go

2024-09-20 21:45 UTC, argha-dot commented on hosted-frontend/src/queries/infrastructure/deployment/mod.rs
> +pub fn udpdate_deployment_query() -> Action<
Fixed the typo, in a commit which has a typo

2024-09-20 21:48 UTC, rakshith-ravi commented on hosted-frontend/src/queries/infrastructure/deployment/mod.rs
> +pub fn udpdate_deployment_query() -> Action<
GG

2024-09-20 21:49 UTC, merged